config/routes.rb
Rails.application.routes.draw do
  resources :doughnuts

  root to: 'doughnuts#home'
  

end

app/models/doughnut.rb
class Doughnut < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/doughnuts_controller.rb
class DoughnutsController < ApplicationController
  before_action :set_doughnut, only: [:show, :edit, :update, :destroy]

  def home
  end

  # GET /doughnuts
  # GET /doughnuts.json
  def index
    @doughnuts = Doughnut.all
  end

  # GET /doughnuts/1
  # GET /doughnuts/1.json
  def show
  end

  # GET /doughnuts/new
  def new
    @doughnut = Doughnut.new
  end

  # GET /doughnuts/1/edit
  def edit
  end

  # POST /doughnuts
  # POST /doughnuts.json
  def create
    @doughnut = Doughnut.new(doughnut_params)

    respond_to do |format|
      if @doughnut.save
        format.html { redirect_to @doughnut, notice: 'Doughnut was successfully created.' }
        format.json { render :show, status: :created, location: @doughnut }
      else
        format.html { render :new }
        format.json { render json: @doughnut.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doughnuts/1
  # PATCH/PUT /doughnuts/1.json
  def update
    respond_to do |format|
      if @doughnut.update(doughnut_params)
        format.html { redirect_to @doughnut, notice: 'Doughnut was successfully updated.' }
        format.json { render :show, status: :ok, location: @doughnut }
      else
        format.html { render :edit }
        format.json { render json: @doughnut.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doughnuts/1
  # DELETE /doughnuts/1.json
  def destroy
    @doughnut.destroy
    respond_to do |format|
      format.html { redirect_to doughnuts_url, notice: 'Doughnut was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doughnut
      @doughnut = Doughnut.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doughnut_params
      params.require(:doughnut).permit(:name, :description, :dough, :diet, :cost, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doughnuts_helper.rb
module DoughnutsHelper
end

app/views/doughnuts/_form.html.erb
<%= form_for(@doughnut) do |f| %>
  <% if @doughnut.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doughnut.errors.count, "error") %> prohibited this doughnut from being saved:</h2>

      <ul>
      <% @doughnut.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :dough %><br>
    <%= f.text_field :dough %>
  </div>
  <div class="field">
    <%= f.label :diet %><br>
    <%= f.text_field :diet %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.number_field :cost %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doughnuts/edit.html.erb
<h1>Editing Doughnut</h1>

<%= render 'form' %>

<%= link_to 'Show', @doughnut %> |
<%= link_to 'Back', doughnuts_path %>

app/views/doughnuts/home.html.erb
<div class="jumbotron">

	<center>

		<img src="http://s23.postimg.org/9dv9dnicr/doughnoz_01.png">

		<h2 class="highlight">There's no place like a Doughnut Shop</h2>
		<h1 style"color:white;">doughnOZ.</h1>

		
		<br>

		<h4>We specialize in gourmet doughnuts that only a Wonderful Wizard could imagine.</h4>

		<h4>So have a heart, use your brain, be courageous and follow the yellow brick road to 123 Main St. Kansas City, Kansas</h4>

		<%= link_to "View Today's Doughnuts!", doughnuts_path, class: "btn btn-success" %>
	</center>

</div>

app/views/doughnuts/index.html.erb
<h1><span class="highlight">Today's Magical Doughnuts</span></h1>
<div class="row">
<% @doughnuts.each do |doughnut| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="<%= doughnut.image %>">
      <div class="caption">
        <h3><%= doughnut.name %></h3>
        <h3>Cost: $<%= doughnut.cost %></h3>
        <%= link_to "View More", doughnut, class: "btn btn-success" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

<br>


<%= link_to 'New Doughnut', new_doughnut_path, class: "btn btn-primary" %>

app/views/doughnuts/new.html.erb
<h1>New Doughnut</h1>

<%= render 'form' %>

<%= link_to 'Back', doughnuts_path %>

app/views/doughnuts/show.html.erb
<div class="jumbotron">
  <center>
    <h1><%= @doughnut.name %></h1>
    <img src="<%= @doughnut.image %>" class="img-responsive">
  </center>
  <h3>Description: <%= @doughnut.description %></h3>
  <h3>Dough: <%= @doughnut.dough %></h3>
  <h3>Diet: <%= @doughnut.diet %></h3>
  <h3>Cost: $<%= @doughnut.cost %></h3>
</div>

<%= link_to 'Edit', edit_doughnut_path(@doughnut) %> |
<%= link_to 'Back', doughnuts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>DoughnutShoppe</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/readable/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Doughnuts", doughnuts_url %></li>
        <li><a href="#">About</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>